export const C = {
  FPS: 60,
  JUMP_SQUAT: 3,
  DASH_FRAMES: 12,
  SKID_FRAMES: 8,
  RUN_TURN_FRAMES: 10,
  LAND_LAG: 4,
  HELPLESS_LAND_LAG: 24,
  BUFFER: 6,
  FLICK_WINDOW: 4,
  SMASH_CHARGE_MAX: 60,
  SMASH_CHARGE_MUL: 0.4,
  SHIELD_MAX: 50,
  SHIELD_DRAIN: 0.15,
  SHIELD_REGEN: 0.08,
  SHIELD_HIT_MUL: 1.19,
  SHIELD_DROP: 6,
  SHIELD_BREAK_STUN: 300,
  SHIELD_BREAK_MIN: 60,
  PARRY_WINDOW: 3,
  PARRY_FRAMES: 8,
  SPOT_DODGE: { start: 2, invuln: 20, total: 26 },
  ROLL: { start: 4, invuln: 22, total: 32, dist: 110 },
  AIR_DODGE: { start: 3, invuln: 27, total: 38, land: 10, speed: 9 },
  TUMBLE_KB: 80,
  HITSTUN_MUL: 0.4,
  KB_TO_VEL: 0.143,
  LAUNCH_DECAY: 0.1,
  HITLAG_BASE: 4,
  HITLAG_PER_DMG: 0.65,
  HITLAG_MAX: 24,
  DI_MAX: 18,
  LEDGE_INVULN: 40,
  LEDGE_HANG_MAX: 180,
  LEDGE_COOLDOWN: 30,
  LEDGE_CLIMB: 20,
  LEDGE_ROLL: 30,
  LEDGE_JUMP: 8,
  GRAB_TIMER_BASE: 100,
  GRAB_TIMER_MIN: 40,
  MASH_VALUE: 6,
  PUMMEL_DAMAGE: 3,
  KNOCKDOWN_MAX: 60,
  GETUP: 22,
  GETUP_ROLL: 30,
  TECH_WINDOW: 20,
  TECH_FRAMES: 12,
  TECH_ROLL: 26,
  /** Tumbling into the floor faster than this, still in hitstun and not teched, bounces back up at GROUND_BOUNCE of the speed. */
  GROUND_BOUNCE_SPEED: 11,
  GROUND_BOUNCE: 1,
  /** How fast a spike's downward speed bleeds back to fall speed, per frame. */
  SPIKE_DECAY: 1,
  RESPAWN_FRAMES: 90,
  RESPAWN_PLATFORM: 120,
  RESPAWN_INVULN: 120,
  DEAD_FRAMES: 90,
  KO_SLOWMO: 20,
  TAUNT: 60,
  WALL_JUMP_VX: 7,
  WALL_JUMP_VY: 13,
  FOOTSTOOL_VY: 12,
  SUDDEN_DEATH_PERCENT: 300,
  DASH_ATTACK_MIN_RUN: 4,
} as const;
